version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /app    
        volumes:
            - ./app:/app
            - ./app/config/php.ini:/usr/local/etc/php/php.ini
             - ./app/error_logs:/var/log/php


